config/routes.rb
Rails.application.routes.draw do

  post   'login'   => 'sessions#login'
  delete 'sessions/logout' => 'sessions#destroy'
  get 'joins/:id/join' => 'joins#join'
  get 'joins/:id/cancel' => 'joins#cancel'
  post 'add_user' => 'joins#join'
  delete 'destroy_rsvp' => 'joins#cancel'
  root 'users#new'
  resources :users, only: [:main, :show, :new, :create]
  resources :trips, only: [:show, :new, :create, :join]

  resources :joins, only: [:join, :cancel]

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :travellers, through: :joins, source: :user


  validates :destination, presence: true
  validates :user_id,  :start_date, :end_date, presence: true
  validates_date :start_date, on_or_after: lambda { Date.current }

  validates_date :end_date, :after => :start_date

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :trips
  has_many :joins
  has_many :trips_joined, through: :joins, source: :trips

  validates :username, presence: true,
            uniqueness: {case_sesnsitive: false},
            length: { minimum: 3, maximum: 30}
  validates :name,  presence: true, length: {minimum: 2, maximum: 50 }
  validates :password, presence: true, length: { minimum: 8 }

    def user_already_added?(trip_id, current_user)
      joins.where(trip_id: trip_id, user_id: current_user).count < 1
    end
    def user_added(trip_id)
      joins.where(trip_id: trip_id).count == 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def logged_in
    redirect_to '/events' if session[:user_id]
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  def joined_trip trip_id
    Join.find_by(user_id: session[:user_id], trip_id: trip_id) if session[:user_id]
  end

  helper_method :joined_trip
  def require_login
    redirect_to '/users' if session[:user_id] == nil
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  def join
    @join = Trip.find(params[:join])
    joins = current_user.joins.create(trip_id: @join.id, user_id: current_user.id)
    if joins.save
      flash[:success] = "You have joined the trip!"
    redirect_to :back

  else
    flash[:error] = "You have not joined the trip!"
    redirect_to :back
  end

  end
  def cancel
    joined_trip = Join.find_by(user_id: session[:user_id], trip_id: params[:id])
    joined_trip.destroy
    flash[:success] = "You have been removed from the trip!"
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Welcome back."
      redirect_to user
    else
      flash[:danger] = "Invalid username/password combination"
      redirect_to :back
    end
  end

  def destroy
    log_out
    flash[:success] = "You have successfully logged out."
    redirect_to root_url
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def new
    @trip = Trip.new
  end
  def create
      @trip = current_user.trips.create(trip_params)
      join = Join.create(user_id: session[:user_id], trip: @trip)
    if @trip.save
      flash[:success]="Your trip has been added!"
      redirect_to user_path(current_user)
    else
      # flash[:errors] = @trip.errors.full_messages
      # puts "wakka wakka"
      # puts @trip.errors.full_messages

      render :new
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @joins = Join.where(trip_id: @trip.id)

  end
  private
  def trip_params
    user_id = current_user
    params.require(:trip).permit(:destination, :description, :start_date, :end_date, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @other_trips = Trip.all.where.not(user_id: @user)
    @my_trips = Join.where(user: current_user).joins(:trip)
  end

  def create
      @user = User.create(user_params)
      if @user.save
        log_in @user

          flash[:success] = "Welcome to the club."
          redirect_to @user
      else
          render :new
      end
  end

  def destroy
    log_out
    flash[:success] = "You have successfully logged out."
    redirect_to root_url
  end

  private
  def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def log_out
    session.delete(:user_id)
    @current_user=nil
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">

    <% if current_user %>
    <%= link_to "Home", user_path(current_user), class: "navbar-brand"%>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My Trips", user_path(current_user) %></li>
          <li><%= link_to "Add Trip", new_trip_path  %></li>
        </ul>
        <ul class = "nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <p>Logged in as: <strong><%= current_user.username.present? ? current_user.username : current_user.name %></strong></p>
          </li>
          <li class = "col-md-4 logout"><%= link_to("Logout", sessions_logout_path, class: "btn btn-xs btn-danger", method: :delete) %> </li>

        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelplans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navigation' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
    </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/trips/new.html.erb
<h1>Add a New Trip:</h1>

<div class = "row">
  <div class ="col-md-8">

    <%= form_for (@trip) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :destination %>
    <%= f.text_field :destination, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.label :start_date %>
    <%=f.date_field :start_date, class: 'form-control'  %>

    <%= f.label :end_date, "End Date" %>
    <%= f.date_field :end_date, class: 'form-control' %><br>

    <%= f.submit "Add", class: "btn btn-success" %>

    <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<h2>Trip Details</h2>

<dl class = "dl-horizontal">
  <dt><strong>Destination:</strong></dt>
  <dd><%= @trip.destination %></dd>
  <dt><strong>Organized By:</strong></dt>
  <dd><%= @trip.user.name %></dd>
  <dt><strong>The Plan:</strong></dt>
  <dd><%= @trip.description %></dd>
  <dt><strong>Start Date:</strong></dt>
  <dd><%= @trip.start_date.strftime("%B %d %Y") %></dd>
  <dt><strong>End Date:</strong></dt>
  <dd><%= @trip.end_date.strftime("%B %d %Y") %></dd>
</dl>

<h4> Other Users Joining the Trip:</h4>

<% @joins.each do |join| %>
  <ul>
    <h5><li><%= join.user.name %></li></h5>
  </ul>
  <% end %>
  <% if current_user.user_already_added?(@trip.id, current_user.id) %>
    <%= link_to "Join Trip", add_user_path(user: current_user, join: @trip.id),
                  class: "btn btn-primary",
                  method: :post %>
  <% else %>

      <button class ="btn btn-danger"><a href="/joins/<%= @trip.id %>/cancel" >Cancel</a></button>

  <% end %>

app/views/users/new.html.erb
<h1>Welcome!</h1>
<h3>Login:</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: 'login') do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
<h3> Register: </h3>

  <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.text_field :password_confirmation, class: 'form-control' %><br>

        <%= f.submit "Register", class: "btn btn-success" %>

        <% end %>
    </div>

</div>

app/views/users/show.html.erb
<h1>Hello there, <%= @user.name %>!</h1>



<div class="row">
  <div class="col-md-10">

        <h3>Your Planned Trips</h3>
    <table class="table table-striped">
        <tr>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date </th>
            <th>Description</th>

        </tr>
        <% @my_trips.each do |x| %>
        <tr>

            <td><a href="/trips/<%= x.trip.id%>" ><%= x.trip.destination %></a></td>
            <td><%= x.trip.start_date.strftime("%B %d %Y")%></td>
            <td><%= x.trip.end_date.strftime("%B %d %Y") %></td>
            <td><%= x.trip.description %></td>

        </tr>
        <% end %>
    </table>


    <h2>Other User's Travel Plans</h2>
    <table class="table table-striped">
        <tr>
            <th>Organizer</th>
            <th>Destination</th>
            <th>Travel Start Date </th>
            <th>Travel End Date </th>
            <th>Do you want to join?</th>

        </tr>
        <% if @other_trips.any?  %>
        <% @other_trips.each do |x| %>
        <tr>

            <td><%= x.user.name %></td>
            <td><a href="/trips/<%= x.id%>" ><%= x.destination %></a></td>
            <td><%= x.start_date.strftime("%B %d %Y") %></td>
            <td><%= x.end_date.strftime("%B %d %Y") %></td>
            <% if current_user.user_already_added?(x.id, current_user.id) %>
            <td><%= link_to "Join Trip", add_user_path(user: current_user, join: x.id),
                          class: "btn btn-primary btn-xs",
                          method: :post %></td>
            <% else %>
             <td><p>Already Joined</p></td>
             <% end %>

        </tr>
        <% end %>
    </table>
    <% end %>

</div>